import { defineConfig, type OverrideOutput } from 'orval';

const createHeader: OverrideOutput['header'] = (info) => [
  'Generated by Orval 🍺',
  'Do not edit manually.',
  ...(info.title ? [info.title] : []),
  ...(info.description ? [info.description] : []),
  ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
  'biome-ignore-all lint: due to automatically generated contents',
];

const INPUT_FILE = './openapi.yaml';
const OUTPUT_DIR = './src/libs/generated';

export default defineConfig({
  fether: {
    input: INPUT_FILE,
    output: {
      target: `${OUTPUT_DIR}/clients`,
      namingConvention: 'kebab-case',
      mode: 'tags',
      client: 'fetch',
      baseUrl: 'https://yumemi-frontend-engineer-codecheck-api.vercel.app',
      clean: true,
      biome: true,
      override: {
        header: createHeader,
      },
    },
  },
  zod: {
    input: INPUT_FILE,
    output: {
      target: `${OUTPUT_DIR}/schemas`,
      namingConvention: 'kebab-case',
      mode: 'tags',
      client: 'zod',
      clean: true,
      biome: true,
      override: {
        header: createHeader,
      },
    },
  },
});
