import { CookiesNextProvider } from 'cookies-next';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { SiteThemeProvider } from '../features/site-theme/providers';
import { getSiteThemeFromCookies } from '../features/site-theme/server/cookies';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getSiteThemeFromCookies();
  return (
    <html data-theme={theme} lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CookiesNextProvider
          pollingOptions={{ enabled: true, intervalMs: 1000 }}
        >
          <SiteThemeProvider value={theme}>{children}</SiteThemeProvider>
        </CookiesNextProvider>
      </body>
    </html>
  );
}
